### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by zafixdata** [zafixdata/YY#11]
- [x] P_manager Dev
- [x] P_manager Test
- [x] Custom Config Loading using cli args
- [ ] Custom Folder Test using cli args (-t)
- [ ] Custom Folder Continue using cli args (-c)
- [ ] Pytorch Time Profile Vs Tensorflow
